### ISSUE TITLE
Lab list is not discoverable

### ISSUE THREAD

**Issue by kcarnold** [integrated-ethics/web#6]
- [x] a link to some lab should be visible without scrolling
- [x] the "Labs" link on the navbar should work

**Comment by rpruim** [comment]
I'm going to close this for now since we have something minimally meeting these criteria.  We can re-open or open a new issue regarding exactly what we want on the labs/ page.

Note:  I edited the list.html layout template so that only labs with a publishdate before the current date and after 2021-07-01 will be listed.  This gives us a way to keep things off the list until we are ready.  Edit the `publishdate` field in the yaml to set the publish date.  I think it will use `date` if there is no `publishdate` listed.  (Should probably test this.). 

@kcarnold, the `publishdate` should be added to conversion from google.  There is also `draft` that we could use to indicate that something is in draft state.  Perhaps that would be better.  (We could still set publish date to a future date to delay when something shows up.)
